package handlers

import "strings"

// blockedEmailDomains is a list of known disposable, temporary, and spam
// email domains. Registration from these domains is rejected.
// Maintain alphabetically for easy lookup when adding new entries.
var blockedEmailDomains = map[string]struct{}{
	"0-mail.com":          {},
	"027168.com":          {},
	"10minutemail.com":    {},
	"20minutemail.com":    {},
	"33mail.com":          {},
	"binkmail.com":        {},
	"bitaddress.org":      {},
	"boun.cr":             {},
	"bugmenot.com":        {},
	"burnermail.io":       {},
	"clickdeal.co":        {},
	"clipmail.eu":         {},
	"crazymailing.com":    {},
	"deadaddress.com":     {},
	"discard.email":       {},
	"discardmail.com":     {},
	"discardmail.de":      {},
	"disposable.email":    {},
	"disposableemailaddresses.emailmiser.com": {},
	"drdrb.com":           {},
	"dropmail.me":         {},
	"dumpandjunk.com":     {},
	"emaildrop.io":        {},
	"emailfake.com":       {},
	"emailisvalid.com":    {},
	"emailondeck.com":     {},
	"emailsensei.com":     {},
	"emailtemporario.com.br": {},
	"fakeinbox.com":       {},
	"fakemail.fr":         {},
	"fakemailgenerator.com": {},
	"fastservice.com":     {},
	"filzmail.com":        {},
	"flymail.tk":          {},
	"get2mail.fr":         {},
	"getnada.com":         {},
	"getonemail.com":      {},
	"getonemail.net":      {},
	"guerrillamail.biz":   {},
	"guerrillamail.com":   {},
	"guerrillamail.de":    {},
	"guerrillamail.info":  {},
	"guerrillamail.net":   {},
	"guerrillamail.org":   {},
	"guerrillamailblock.com": {},
	"harakirimail.com":    {},
	"hmamail.com":         {},
	"incognitomail.org":   {},
	"jetable.org":         {},
	"jourrapide.com":      {},
	"kasmail.com":         {},
	"koszmail.pl":         {},
	"kurzepost.de":        {},
	"linshiyouxiang.net":  {},
	"lroid.com":           {},
	"maildrop.cc":         {},
	"mailexpire.com":      {},
	"mailforspam.com":     {},
	"mailin8r.com":        {},
	"mailinator.com":      {},
	"mailinator.net":      {},
	"mailinator2.com":     {},
	"mailincubator.com":   {},
	"mailme.lv":           {},
	"mailnesia.com":       {},
	"mailnull.com":        {},
	"mailsac.com":         {},
	"mailslurp.com":       {},
	"mailtemp.info":       {},
	"mailtothis.com":      {},
	"mailzilla.com":       {},
	"mintemail.com":       {},
	"mohmal.com":          {},
	"mvrht.net":           {},
	"mytemp.email":        {},
	"mytrashmail.com":     {},
	"nada.email":          {},
	"nobulk.com":          {},
	"nospam.ze.tc":        {},
	"notmailinator.com":   {},
	"notsharingmy.info":   {},
	"nowmymail.com":       {},
	"ownmail.net":         {},
	"purcell.email":       {},
	"recodz.com":          {},
	"reddithub.com":       {},
	"sharklasers.com":     {},
	"shieldedmail.com":    {},
	"spamavert.com":       {},
	"spambox.us":          {},
	"spamcowboy.com":      {},
	"spamcowboy.net":      {},
	"spamcowboy.org":      {},
	"spamgourmet.com":     {},
	"spamgourmet.net":     {},
	"spamgourmet.org":     {},
	"spamherelots.com":    {},
	"spamhereplease.com":  {},
	"spamthisplease.com":  {},
	"superrito.com":       {},
	"temp-mail.org":       {},
	"tempail.com":         {},
	"tempemail.co.za":     {},
	"tempemail.net":       {},
	"tempinbox.com":       {},
	"tempmail.com":        {},
	"tempmail.eu":         {},
	"tempmail.it":         {},
	"tempmail.net":        {},
	"tempmail2.com":       {},
	"tempmailaddress.com": {},
	"tempmailer.com":      {},
	"tempomail.fr":        {},
	"temporaryemail.net":  {},
	"temporaryemail.us":   {},
	"temporaryforwarding.com": {},
	"temporarymail.org":   {},
	"thanksnospam.info":   {},
	"throwam.com":         {},
	"throwaway.email":     {},
	"throwawayemailaddress.com": {},
	"trashmail.at":        {},
	"trashmail.com":       {},
	"trashmail.io":        {},
	"trashmail.me":        {},
	"trashmail.net":       {},
	"trashmail.org":       {},
	"trbvm.com":           {},
	"trbvn.com":           {},
	"tryninja.io":         {},
	"tttttmail.com":       {},
	"twinmail.de":         {},
	"uggsrock.com":        {},
	"veryrealemail.com":   {},
	"wh4f.org":            {},
	"yopmail.com":         {},
	"yopmail.fr":          {},
	"yopmail.net":         {},
	"zeroe.ml":            {},
	"zippiex.com":         {},
}

// isBlockedEmailDomain checks if the email address uses a blocked disposable domain.
func isBlockedEmailDomain(email string) bool {
	parts := strings.SplitN(email, "@", 2)
	if len(parts) != 2 {
		return false
	}
	domain := strings.ToLower(strings.TrimSpace(parts[1]))
	_, blocked := blockedEmailDomains[domain]
	return blocked
}
